### ISSUE TITLE
ExoticGarden ID Conflict[BUG]

### ISSUE THREAD

**Issue by AnhedonicNeko** [ClayCoffee/ClayTech#1]
** Describe 描述 **
ClayTech and ExoticGarden currently share two IDs: LEMON and SWEETPOTATO

** To Reproduce 如何复现 **
Install both ClayTech (20200316 nightly) and ExoticGarden (DEV 37 (git 76bd2)

** Running Environment 运行环境 **
Minecraft 1.15.2, Paper 137, Spigot 1.15.2 (buildtools 112), Forge 31.1.18

** Screenshots 截图 **
![image](https://user-images.githubusercontent.com/62277916/76828301-0499e900-67f7-11ea-9a61-87095f1b09b0.png)

**Comment by ClayCoffee** [comment]
OK.Fixed this issue. Thank you!
