### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [ClayCoffee/ClayTech#102]
** Describe 描述 **
使用了Paper 1.16.4的服务端，但是他提醒我用的不是1.13.x，1.14.x，1.15.x，1.16.x的版本

** Running Environment 运行环境 **
Paper #414版

** Screenshots 截图 **
[https://ae01.alicdn.com/kf/U43258515378544349d34753d5a55ba18F.jpg](url)

**Comment by ClayCoffee** [comment]
更新 Slimefun 版本 和 ClayTech 版本
