### ISSUE TITLE
[BUG] 控制台反馈

### ISSUE THREAD

**Issue by SueFox** [ClayCoffee/ClayTech#107]
** Describe 描述 **
控制台反馈

** To Reproduce 如何复现 **

** Running Environment 运行环境 **
jre1.8.0_281
** Screenshots 截图 **
![X_QDB4W Q@PLCG76CJVMZ6C](https://user-images.githubusercontent.com/71171999/106104180-0c4b4d80-617d-11eb-8e51-9744ce310e5d.png)

这是文件：
链接：https://pan.baidu.com/s/1IAYOE9DySyHggTluZCHNOA 
提取码：zfhw

**Comment by ClayCoffee** [comment]
Slimefun 版本太旧。 SKIP 无效
