### ISSUE TITLE
[BUG]主插件即将移除一个方法

### ISSUE THREAD

**Issue by kuzuanpa** [ClayCoffee/ClayTech#116]
** Describe 描述 **
似乎slimefun主插件即将移除一个传递方法

** To Reproduce 如何复现 **
只需以新版slimefun运行本插件即可

** Running Environment 运行环境 **
paper核心 1.16.5
slimefun汉化版v4.9-canary-fb2fbce
claytech1.2.21

** Screenshots 截图 **
![QQ截图20210505224937](https://user-images.githubusercontent.com/61902985/117161024-2fc50a80-adf4-11eb-9e68-a930fbb874f1.png)

**Comment by Xzavier0722** [comment]
我修复了与新版的兼容，可以在[这里](https://github.com/Xzavier0722/ClayTech/releases)下载试一下。

**Comment by MCZQ** [comment]
> 德金·德克特·德金

好家伙，非常感谢！我解决昨天下午弄了一下午这个问题，而且貌似与异域花园也不兼容，不知道您有没有注意到？

**Comment by Xzavier0722** [comment]
> > 德金·德克特·德金
> 
> 好家伙，非常感谢！我解决昨天下午弄了一下午这个问题，而且貌似与异域花园也不兼容，不知道您有没有注意到？

如果是与粘土冲突的话，麻烦提供一下报错。最好可以在我的fork里的issue反馈。

**Comment by MCZQ** [comment]
我也不清楚是不是与粘土冲突，反正加载完claytech之后异域花园就dis了，是不是新版本的sf的api与异域花园有冲突？

[16:31:17] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 75 (git 6c3e5412)

[16:31:17] [Server thread/ERROR]: Error occurred while enabling ExoticGarden vDEV - 75 (git 6c3e5412) (Is it up to date?)

java.lang.NoSuchMethodError: io.github.thebusybiscuit.slimefun4.api.items.ItemSetting.<init&gt;(Lme/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem;Ljava/lang/String;Ljava/lang/Object;)V

	at io.github.thebusybiscuit.exoticgarden.items.BonemealableItem.<init&gt;(BonemealableItem.java:19) ~[?:?]

	at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerBerry(ExoticGarden.java:308) ~[?:?]

	at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerItems(ExoticGarden.java:112) ~[?:?]

	at io.github.thebusybiscuit.exoticgarden.ExoticGarden.onEnable(ExoticGarden.java:87) ~[?:?]

	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"]

	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

[16:31:17] [Server thread/INFO]: [ExoticGarden] Disabling ExoticGarden vDEV - 75 (git 6c3e5412)

**Comment by Xzavier0722** [comment]
> 我也不清楚是不是与粘土冲突，反正加载完claytech之后异域花园就dis了，是不是新版本的sf的api与异域花园有冲突？ [16:31:17] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 75 (git 6c3e5412) [16:31:17] [Server thread/ERROR]: Error occurred while enabling ExoticGarden vDEV - 75 (git 6c3e5412) (Is it up to date?) java.lang.NoSuchMethodError: io.github.thebusybiscuit.slimefun4.api.items.ItemSetting.<init&gt;(Lme/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem;Ljava/lang/String;Ljava/lang/Object;)V at io.github.thebusybiscuit.exoticgarden.items.BonemealableItem.<init&gt;(BonemealableItem.java:19) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerBerry(ExoticGarden.java:308) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerItems(ExoticGarden.java:112) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.onEnable(ExoticGarden.java:87) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] [16:31:17] [Server thread/INFO]: [ExoticGarden] Disabling ExoticGarden vDEV - 75 (git 6c3e5412)

这个是和sf不兼容。

**Comment by MCZQ** [comment]
> > 我也不清楚是不是与粘土冲突，反正加载完claytech之后异域花园就dis了，是不是新版本的sf的api与异域花园有冲突？ [16:31:17] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 75 (git 6c3e5412) [16:31:17] [Server thread/ERROR]: Error occurred while enabling ExoticGarden vDEV - 75 (git 6c3e5412) (Is it up to date?) java.lang.NoSuchMethodError: io.github.thebusybiscuit.slimefun4.api.items.ItemSetting.<init>(Lme/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem;Ljava/lang/String;Ljava/lang/Object;)V at io.github.thebusybiscuit.exoticgarden.items.BonemealableItem.<init>(BonemealableItem.java:19) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerBerry(ExoticGarden.java:308) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerItems(ExoticGarden.java:112) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.onEnable(ExoticGarden.java:87) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] [16:31:17] [Server thread/INFO]: [ExoticGarden] Disabling ExoticGarden vDEV - 75 (git 6c3e5412)
> 
> 这个是和sf不兼容。

好的，谢谢

**Comment by kuzuanpa** [comment]
> 我也不清楚是不是与粘土冲突，反正加载完claytech之后异域花园就dis了，是不是新版本的sf的api与异域花园有冲突？ [16:31:17] [Server thread/INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 75 (git 6c3e5412) [16:31:17] [Server thread/ERROR]: Error occurred while enabling ExoticGarden vDEV - 75 (git 6c3e5412) (Is it up to date?) java.lang.NoSuchMethodError: io.github.thebusybiscuit.slimefun4.api.items.ItemSetting.<init&gt;(Lme/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem;Ljava/lang/String;Ljava/lang/Object;)V at io.github.thebusybiscuit.exoticgarden.items.BonemealableItem.<init&gt;(BonemealableItem.java:19) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerBerry(ExoticGarden.java:308) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.registerItems(ExoticGarden.java:112) ~[?:?] at io.github.thebusybiscuit.exoticgarden.ExoticGarden.onEnable(ExoticGarden.java:87) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"a0aa5ab"] at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] [16:31:17] [Server thread/INFO]: [ExoticGarden] Disabling ExoticGarden vDEV - 75 (git 6c3e5412)

这是新版sf跟异域花园不兼容，你可以去ExoticGarden那边看看，如果开发者还在维护这个应该是已经修了的（sf官方似乎2个月前在加载的时候就有警告了）
