### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MrBaggy99** [ClayCoffee/ClayTech#12]
** Describe 描述 **
the plugin stopped working, I tried reinstalling and I never touched the config or anything. it might because of the recent slime fun update? I'm not sure

** To Reproduce 如何复现 **
starting the server

** Running Environment 运行环境 **

** Screenshots 截图 **

**Comment by ClayCoffee** [comment]
err logs

**Comment by ClayCoffee** [comment]
No response
