### ISSUE TITLE
[BUG] Error occurred while enabling ClayTech v1.1.6 

### ISSUE THREAD

**Issue by PhantumOne** [ClayCoffee/ClayTech#14]
Error occurred while enabling ClayTech v1.1.6 (Is it up to date?)
java.lang.NoSuchFieldError: BASIC_MACHINES

https://pastebin.com/BGcVy9aF

**Installed current build of SlimeFun4 and all addon's for PaperMC1.15.2 including ClayTech**

You are running the latest version!
Paper v1_15_R1

CS-CoreLib vDEV - 84 (git 0d29dbee)
Slimefun vDEV - 487 (git ca6170e6)

Installed Addons (19)
DyedBackpacks vDEV - 5 (git 129670c7)
SoundMuffler vDEV - 10 (git 545192ca)
SlimefunOreChunks vDEV - 8 (git 41e31ffc)
ExtraToolsPlugin vDEV - 9 (git 84269b5a)
SlimeXpansion vDEV - 15 (git 57438f88)
HotbarPets vDEV - 26 (git 7489ae00)
ExtraGear vDEV - 9 (git e851d81d)
SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)
ExoticGarden vDEV - 39 (git 43a30365)
Barrels vDEV - 11 (git abecba9c)
ElectricSpawners vDEV - 10 (git 6c891f7f)
ExtraHeads vDEV - 14 (git 596a0822)
WhatIsThis v2.9
SoulJars vDEV - 15 (git dd58f105)
MobCapturer vDEV - 7 (git b61d3fbf)
SlimyTreeTaps vDEV - 10 (git 66d1dd72)
PrivateStorage vDEV - 11 (git b064863b)
ColoredEnderChests vDEV - 12 (git 8dbdc909)
ChestTerminal vDEV - 30 (git 04393688)

Plugins (85): AuctionHouse, AutomaticInventory, AutoPickup, Barrels, BeaconPlus2*, BeehivesPro, BetterShulkerBoxes, BKCommonLib, ChestTerminal, ClearLag, ColoredEnderChests, CommandSigns, CraftBook, CS-CoreLib, CustomCobbleGen, CustomEnderChest, DyedBackpacks, ElectricSpawners, EmeraldEnchants, EntityTrackerFixer, EpicFarming, EpicFurnaces, EpicHoppers, EpicSpawners, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExoticGarden, ExtraGear, ExtraHeads, ExtraToolsPlugin, FabledSkyBlock, GriefPrevention, GSit, GUIWarps, HolographicDisplays, HotbarPets, IronicChest, Jobs, JoinMessagePlus*, LightAPI*, LimitPillagers, LuckPerms, MeteoritesPro, MobCapturer, MorphMining, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MySkin, PickupArrows, PlaceholderAPI, PrivateStorage, ProtectionLib*, ProtocolLib, Realistic-Swimming, ShinyItems, ShopGUIPlus, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimeXpansion, SlimyTreeTaps, SoulJars, SoundMuffler, TabList, TCCoasters, Train_Carts, TridentCraft, UltimateFishing, UltimateKits, UltimateRepairing, UltimateStacker, UltimateTimber, Vault, VeinMiner, volcano, WhatIsThis, Wild, WorldEdit, WorldGuard, WorldSpawn*, XP-Deposit*

** Toshiba Qosimo Gaming Laptop with Windows 8.1 OS, 16GB RAM, i7 Quad Core processor dual 1TB SATA Drives and Gigabit Network adapter running at 250 Mbps**

Minecraft: PaperMC 1.15.2 build 208
                 java -Xmx6G -jar paper-208.jar nogui

** No screen shots available (log posted above) **

**Comment by ClayCoffee** [comment]
fixed
