### ISSUE TITLE
[BUG]Can't Inject Fuel into Rocket.

### ISSUE THREAD

**Issue by ItWasTheEgg** [ClayCoffee/ClayTech#15]
** Describe 描述 **
Mixed rocket fuel will not go into the rocket.

** To Reproduce 如何复现 **
Put Rocket and Mixed fuel inside Rocket Fuel Injector.

** Running Environment 运行环境 **
CraftBukkit version git-Spigot-a03bifd-f7d6ad5 (MC: 1.15.2)

** Screenshots 截图 **
![2020-04-26_20 04 13](https://user-images.githubusercontent.com/33503627/80323407-35f3d480-87f9-11ea-8a87-e014207b0e73.png)
![2020-04-26_20 04 27](https://user-images.githubusercontent.com/33503627/80323409-37250180-87f9-11ea-94f2-c900e4c5a077.png)
![2020-04-26_20 04 28](https://user-images.githubusercontent.com/33503627/80323410-37bd9800-87f9-11ea-97ce-1c7f7935ba57.png)

**Comment by ClayCoffee** [comment]
err logs

**Comment by ItWasTheEgg** [comment]
ok [https://pastebin.com/TbHDfNgz](url)

**Comment by ClayCoffee** [comment]
use Ubuntu Pastebin

**Comment by ItWasTheEgg** [comment]
https://paste.ubuntu.com/p/9yvBTcG4wc/

[https://paste.ubuntu.com/p/9yvBTcG4wc/](url)
