### ISSUE TITLE
[Language Report] Fix en-US.yml misspellings

### ISSUE THREAD

**Issue by MagmaSlime123** [ClayCoffee/ClayTech#2]
Fix all the misspellings for everything.

I know your not English.

**Comment by ClayCoffee** [comment]
Yes, My english is bad
Can you help me?

**Comment by J3fftw1** [comment]
> 
> 
> Fix all the misspellings for everything.
> 
> I know your not English.

you're

**Comment by J3fftw1** [comment]
also ender you should point out what words are incorrect so its easier to fix no way in hell this guy is gonna read every word and see a flaw he will miss stuff pointing out something is wrong but not telling whats wrong is a useless way of reporting an issue

**Comment by ClayCoffee** [comment]
> also ender you should point out what words are incorrect so its easier to fix no way in hell this guy is gonna read every word and see a flaw he will miss stuff pointing out something is wrong but not telling whats wrong is a useless way of reporting an issue

Hey,panda.I know you are a famous Slimefun Addon Maker.
Can you help me with the english language file?

**Comment by J3fftw1** [comment]
I could help but im not gonna read every single word to see if its misspelled
Thats why i commented on this issue. This issue in my eyes in invallid just because there is nothing he actually reported.
Its like saying claytech is broken but not saying what.

**Comment by ClayCoffee** [comment]
[Here](https://gitlocalize.com/repo/4241)  is the translating project.
You can fix the misspellings yourself.
Thank you!
If you don't understand Chinese, I'll fix it myself.

**Comment by j19mes** [comment]
I use ClayTech and i haven't noticed any awful misspellings keep up the great work!
