### ISSUE TITLE
[BUG] Moon is not generating

### ISSUE THREAD

**Issue by OwerWorldPlayer** [ClayCoffee/ClayTech#22]
** Describe 描述 **
When i went to moon it is only overworld

** To Reproduce 如何复现 **

** Running Environment 运行环境 **

** Screenshots 截图 **
![2020-05-08_16 41 40](https://user-images.githubusercontent.com/59805046/81411419-03c46a00-914b-11ea-92a9-7174f7806281.png)
![2020-05-08_16 41 46](https://user-images.githubusercontent.com/59805046/81411432-06bf5a80-914b-11ea-937a-009c719781f1.png)
![2020-05-08_16 42 04](https://user-images.githubusercontent.com/59805046/81411449-0a52e180-914b-11ea-875f-24e69c4cf0ae.png)

**Comment by ClayCoffee** [comment]
Server information

**Comment by ClayCoffee** [comment]
Try to delete the moon world by deleting the world folder

**Comment by OwerWorldPlayer** [comment]
i cant delete my world it is very huge

**Comment by OwerWorldPlayer** [comment]
i deleted moon 5 times but didnt work

**Comment by OwerWorldPlayer** [comment]
my server is 1.15.2 and spigot

**Comment by ClayCoffee** [comment]
plugin version

**Comment by ClayCoffee** [comment]
do you have a multiworld plugin
try remove the moon world information from the plugin config

**Comment by OwerWorldPlayer** [comment]
i have multiversecore

**Comment by OwerWorldPlayer** [comment]
i downloaded lastest

**Comment by ClayCoffee** [comment]
use /mv list and give me the screenshot

**Comment by OwerWorldPlayer** [comment]
i was added it becuase when i didnt add server was crashing
i removed and trying again

**Comment by ClayCoffee** [comment]
remove multiverse-core and try delete the moon world

**Comment by OwerWorldPlayer** [comment]
i did but crashing

**Comment by OwerWorldPlayer** [comment]
it is not giving any error

**Comment by ClayCoffee** [comment]
are you a dunk?
where are the crashing reports

**Comment by ClayCoffee** [comment]
everytime you only give me a little information

**Comment by OwerWorldPlayer** [comment]
what can i give it is not giving error

**Comment by ClayCoffee** [comment]
you said it crashed
 where are the crashing reports?

**Comment by OwerWorldPlayer** [comment]
when i opened moon server is stopping instantly

**Comment by ClayCoffee** [comment]
i think the plugin doesn't have world generating problems
my server is using this plugin and works fine

**Comment by OwerWorldPlayer** [comment]
but when i opened moon it is stopping
now i closed moon and trying to open
Server is opened

**Comment by ClayCoffee** [comment]
??what are you saying

**Comment by OwerWorldPlayer** [comment]
when i opened moon from config server is not opening
but when i closed it 
server is opening
also other planets are working

**Comment by ClayCoffee** [comment]
well, i think this cannot be fixed

**Comment by ClayCoffee** [comment]
my server and other servers work fine
but there is something wrong with your server
it should be your problems

**Comment by OwerWorldPlayer** [comment]
well can i change world file but i will use your rocket
