### ISSUE TITLE
[BUG]All but basic claytech is gone

### ISSUE THREAD

**Issue by threlief** [ClayCoffee/ClayTech#29]
** Describe 描述 **
all but basic claytech not in guide

** To Reproduce 如何复现 **
we tried all the other versions and nothing changed
even updated and downgraded some stuff and nothing 
** Running Environment 运行环境 **
we got all the latest sf stuff on a 1.15.2 server but it wont show up 

** Screenshots 截图 **
sorry my screenshots is broken idk why so here is these
https://discordapp.com/channels/@me/605093234502271009/712079822247034971
https://discordapp.com/channels/@me/605093234502271009/712080251307425963

**Comment by ClayCoffee** [comment]
Now it works fine
