### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shaobaichen** [ClayCoffee/ClayTech#3]
剧毒核心无法合成

**Comment by shaobaichen** [comment]
我用的粘土融合器

**Comment by shaobaichen** [comment]
合成表看了n遍 也供电了

**Comment by ClayCoffee** [comment]
你连详细信息都没给
怎么修复此bug?
经测试，此bug在我本地不存在

**Comment by shaobaichen** [comment]
我没办法发图加我qq 2767955151 真的是合成不了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ClayCoffee"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 晚上6:50
收件人: "ClayCoffee/ClayTech"<ClayTech@noreply.github.com&gt;; 
抄送: "少白晨&amp;"<2767955151@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ClayCoffee/ClayTech] [BUG] (#3)





 
你连详细信息都没给
 怎么修复此bug?
 经测试，此bug在我本地不存在

**Comment by ClayCoffee** [comment]
旧版本，无效问题
