### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nnn950711** [ClayCoffee/ClayTech#37]
** Describe 描述 **
前置都安裝了 但該無法開啟

** To Reproduce 如何复现 **
無法開啟

** Running Environment 运行环境 **
Papermc 1.15.2

** Screenshots 截图 **
![註解 2020-06-07 155535](https://user-images.githubusercontent.com/41001774/83963293-668a5c00-a8d7-11ea-91b1-07ee07811ad8.png)

**Comment by ClayCoffee** [comment]
非bug
1、升级粘土科技版本
2、升级粘液科技版本
