### ISSUE TITLE
TNT爆炸生成器问题

### ISSUE THREAD

**Issue by 1600496156** [ClayCoffee/ClayTech#4]
** Describe 描述 **
手持TNT爆炸生成器右键草方块再破坏已经右键的草方块会掉落多一个TNT爆炸生成器

** To Reproduce 如何复现 **
后台无报错

** Running Environment 运行环境 **
![ZU}QFT@P3(J3$OCV(VG@(1T](https://user-images.githubusercontent.com/62275587/78262713-8dbd5980-7533-11ea-8ea9-d5ba1b4b0992.png)

** Screenshots 截图 **
![FQII}9U{AEQR6_D VJ5(DJH](https://user-images.githubusercontent.com/62275587/78262948-e7be1f00-7533-11ea-948c-f941ec6167be.png)

**Comment by ClayCoffee** [comment]
已修复
解决方法：
更新 1.1.2
删除语言文件
重启
