### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 100petr** [ClayCoffee/ClayTech#40]
** Describe 描述 **
The server is lagging. https://pastebin.com/JZFsh1Ws
On the slimefun discord they wrote me that this is a claytech problem.

** To Reproduce 如何复现 **
Idk, sorry

** Running Environment 运行环境 **
![Screenshot_1](https://user-images.githubusercontent.com/29830635/85162957-6a689780-b262-11ea-87dc-1a9f12089e2f.png)

**Comment by ClayCoffee** [comment]
this is not a bug
just a lag problem
You can disable the moon world

**Comment by ClayCoffee** [comment]
`BlockStorage.addBlockInfo(source.getBlock(tx, ty, tz), "id", "COPPER_ORE",true);`

**Comment by 100petr** [comment]
But what causes those lags? I don't want to turn off the moon, players are already making bases on it.
