### ISSUE TITLE
[BUG] Creates world on start

### ISSUE THREAD

**Issue by Sylvamy** [ClayCoffee/ClayTech#42]
** Describe 描述 **
Decided to add this to my server, upon starting the server this plugin created a "world" folder called "world". Once it had created this world the server would just freeze until force killed so i had to remove it again

** To Reproduce 如何复现 **
Start server with this plugin

** Running Environment 运行环境 **
PaperSpigot-365
Slimefun4 + all addons (apart from this one)

** Screenshots 截图 **

**Comment by ClayCoffee** [comment]
config.yml
change "overworld" value to your main world name
