### ISSUE TITLE
[BUG] Rocket head is old instagram logo

### ISSUE THREAD

**Issue by j19mes** [ClayCoffee/ClayTech#43]
** Describe 描述 **
The rockets head is a old instagram logo, may be better changing it to look like a rocket.

** To Reproduce 如何复现 **
Run ClayTech on any version :)

** Running Environment 运行环境 **
1.15.2 paper

** Screenshots 截图 **
![image](https://user-images.githubusercontent.com/47004779/85345627-d2c9aa00-b4ea-11ea-86c1-8389bb42e2f2.png)

**Comment by Day-OS** [comment]
Same issue here

**Comment by ClayCoffee** [comment]
done
