### ISSUE TITLE
[BUG] Claytech not load

### ISSUE THREAD

**Issue by icansc187** [ClayCoffee/ClayTech#48]
** Describe 描述 **
https://pastebin.com/JJMFYDqb

** To Reproduce 如何复现 **
I just checked console, don't know but multiple plugins had this error too....

** Running Environment 运行环境 **
[+] ClayTech-1.2.0-dev15
[+] CS-CoreLib - DEV 79 (git ec5b4)
[+] Slimefun4 - RC 9 (git c8208)
[+] Paper 1.13.2

** Screenshots 截图 **
https://ibb.co/RNgDJVg

**Comment by icansc187** [comment]
**HelpMe :)**

**Comment by ClayCoffee** [comment]
Use slimefun development version

**Comment by ClayCoffee** [comment]
Do not use the stable version

**Comment by icansc187** [comment]
pleaase give me new version claytech, my claytech error when place lava
bucket or water bucket

Pada tanggal Sab, 4 Jul 2020 pukul 14.32 ClayCoffee <
notifications@github.com> menulis:
