### ISSUE TITLE
[BUG/Not Clear Feature] Spacesuit Oxygen Injector

### ISSUE THREAD

**Issue by DepressedMilkshake** [ClayCoffee/ClayTech#5]
** Describe 描述 **
Space Suit Oxygen Injector does not work, or the description on the item isn't clear enough. It tells me to put leaves above the machine, and I assume i do that and put the spacesuit piece into the machine, which should inject it with oxygen, however, nothing happens. It has power, the suit and the leaves required for the machine to work. Every other machine has worked up to this point, however, I don't want to explore space without filling my spacesuit to stay safe. 
![2020-04-04_21 38 13](https://user-images.githubusercontent.com/63175510/78464879-a5741980-76bc-11ea-8524-7b67dc0620f1.png)

**Comment by ClayCoffee** [comment]
Confirmed.
It is an language bug.
I'll release a new version later.Your server operators should update,delete the original language file and restart the server.

**Comment by ClayCoffee** [comment]
This issue should be fixed now.
