### ISSUE TITLE
[BUG] Error in console when place lava bucket

### ISSUE THREAD

**Issue by icansc187** [ClayCoffee/ClayTech#50]
** Describe 描述 **
https://pastebin.com/ENk8EHmL

** To Reproduce 如何复现 **
Error spam in console

** Running Environment 运行环境 **
[+] ClayTech-1.2.0-dev15
[+] CS-CoreLib - DEV 79 (git ec5b4)
[+] Slimefun4 - DEV 571 (git 768e4)
[+] Paper 1.13.2

** Screenshots 截图 **
https://ibb.co/Mss70Vb

**Comment by ClayCoffee** [comment]
fixed in dev16

**Comment by ClayCoffee** [comment]
It looks like PlayerBucketEvent has been removed in Spigot's API page

**Comment by ClayCoffee** [comment]
update your spigot version

**Comment by icansc187** [comment]
where new version sir
