### ISSUE TITLE
[BUG] ClayTech not working.

### ISSUE THREAD

**Issue by j19mes** [ClayCoffee/ClayTech#54]
** Describe 描述 **
ClayTech does not work with the latest slimefun version.

** To Reproduce 如何复现 **
Slimefun4 - RC 14 (git 47f69)
1.2.0-dev16

** Running Environment 运行环境 **
1.16.1 Paper

** Screenshots 截图 **
https://pastebin.com/HuELz9GY

**Comment by ClayCoffee** [comment]
Please use the latest version.Why the plugin is disabled?

**Comment by FYWindis** [comment]
_https://pastebin.com/0hDXsXur
just the same issue and almost the same environment
seems that error occured when registering items_

update the plugin to dev 17 and bug fixed

sorry to interrupt and thanks for your nice plugin
