### ISSUE TITLE
[BUG]Clay Tech does't work

### ISSUE THREAD

**Issue by Eliwindle** [ClayCoffee/ClayTech#55]
** Describe 描述 **
I did nothing and it suddenly doesn't work

** To Reproduce 如何复现 **
Slimefun4 - v4.3-dev-200705
1.2.0-dev17

** Running Environment 运行环境 **
PAPER-79 and PAPER-93

** Screenshots 截图 **
![QQ图片20200717124558](https://user-images.githubusercontent.com/68413146/87749561-965c4600-c82b-11ea-8740-42f3fedb87f6.png)

**Comment by ClayCoffee** [comment]
汉化版暂不支持

**Comment by ClayCoffee** [comment]
需要那边支持，而不是我这边

**Comment by ClayCoffee** [comment]
要提交问题请去starwishsama那边
