### ISSUE TITLE
A little error while loading [BUG]

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#56]
** Describe 描述 **
Error while loading.

** To Reproduce 如何复现 **
Load server

** Running Environment 运行环境 **
Paper 100, 1.16.1

`[13:42:00 INFO]: [Slimefun] Parent "claytech:claycategory" for Category "claytech:claycategory6" was not found, probably just disabled.`

**Comment by ClayCoffee** [comment]
this is not an error
