### ISSUE TITLE
注册物品出错

### ISSUE THREAD

**Issue by 1600496156** [ClayCoffee/ClayTech#6]
** Describe 描述 **
后台报错，但插件仍能运行

** To Reproduce 如何复现 **
![DPJW0@VJOC6RX8 0ISOAJBJ](https://user-images.githubusercontent.com/62275587/78467110-dd6e7180-773b-11ea-8e9c-da73236979ca.png)

** Running Environment 运行环境 **
![RL9@Z 55`{YU N `LQ1GWZ3](https://user-images.githubusercontent.com/62275587/78467114-e19a8f00-773b-11ea-9e5f-4a378a008113.png)

** Screenshots 截图 **
无

**Comment by ClayCoffee** [comment]
1.1.5
