### ISSUE TITLE
[NewFeature]

### ISSUE THREAD

**Issue by LittleHed** [ClayCoffee/ClayTech#60]
** Describe / 描述 **
1.月球和火星的温度总不可能和地球(主世界)一模一样吧
建议在不同星球上有不同的温度，例如玩家在某星球上如果不拿着特定防寒/抗热 物品/装备 就会进入着火/冰冻状态并造成伤害
2.话说火星地牢啥时候做，或者你可以让我们造地牢，造完保存为.sch文件并放在特定文件夹，插件读取结构文件并在星球上随机生成该结构
3.能不能搞个类似这样的方块:
右键前:
![~3%`GHL${BS9D%~7XGWWEI4](https://user-images.githubusercontent.com/58099834/88300915-9b8f2880-cd36-11ea-82b5-d5d21672d63a.png)
右键后，周围相同的方块都消失了:
![SAD}%@PU3~IE8W1$FKM(I@I](https://user-images.githubusercontent.com/58099834/88300990-b2357f80-cd36-11ea-8b9f-0af5ab121ed5.png)
过几秒(时间可自定义)后重新出现
机制类似暮色森林的再现方块https://www.mcmod.cn/item/3885.html

** How to craft 如何合成 **

**Comment by ClayCoffee** [comment]
安排了
以后可能会做

**Comment by LittleHed** [comment]
> 安排了
> 以后可能会做

还有一个建议，给星球上面的生物头上整个玻璃罩，没有玻璃罩的生物需要呆在特定环境(例如氧气制造机或别的机器附近，还有封闭空间)，否则就会慢慢掉血而死，这个戴上玻璃罩的生物也建议自定义

**Comment by LittleHed** [comment]
话说月球的玩家都有跳跃提升+缓降效果了，不给怪物也整个么

**Comment by ClayCoffee** [comment]
地牢暂时算了，我建不出来；自定义地牢大小不好判断，先搁着吧。

**Comment by ClayCoffee** [comment]
气闸门会安排上的

**Comment by ClayCoffee** [comment]
气闸门好了，其他的以后再说
