### ISSUE TITLE
The electric copier cannot be used

### ISSUE THREAD

**Issue by z924263634** [ClayCoffee/ClayTech#61]
** Describe 描述 **
Putting all kinds of books into the input slot doesn't work. I've tried a lot of combinations.

** To Reproduce 如何复现 **

** Running Environment 运行环境 **

** Screenshots 截图 **

**Comment by ClayCoffee** [comment]
invalid. wrong usage

**Comment by ClayCoffee** [comment]
① book and quill | book and quill
② book | book_and_quill
③ book_and_quill | book
