### ISSUE TITLE
[BUG] Could teleport to moon/mars from end/nether world

### ISSUE THREAD

**Issue by Xzavier0722** [ClayCoffee/ClayTech#63]
** Describe 描述 **
I noticed that the plugin does not allowed player get to moon/mars by using teleporting commands like back/home/tpa/tp etc. In my view, this design is for preventing players cheat by those way, which means it should work like this in end/nether also. But today I found that player could teleport to there by teleporting command (provide by CMI, minecraft:tp also) in nether and end world, which is conflicted with the function design. So I think this should be a bug.

** To Reproduce 如何复现 **
Get to end/nether first, and just use any unusual way (like command) to teleport to these planets.

** Running Environment 运行环境 **
Debian 10.3 with Java 8
git-Paper-116 (MC: 1.16.1)
Essential plugin: CMI
World management plugin: none
Latest release of Slimefun and ClayTech

** Screenshots 截图 **
Null

**Comment by ClayCoffee** [comment]
This is to prevent players from reaching other planets without using rockets, not a bug.

**Comment by Xzavier0722** [comment]
Yes, but why it is allowed player get planets from nether and end world without rockets?

**Comment by ClayCoffee** [comment]
that seems like an issue

**Comment by ClayCoffee** [comment]
confirming

**Comment by ClayCoffee** [comment]
Confirmed.
