### ISSUE TITLE
Timings improvement

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#66]
Hi, is this normal value?

ClayTech::Event: c.c.C.l.FoodEatListener (PlayerInteractEvent)count(1)  total(0.04% 0.008s, 0.10% of tick)avg(7.82ms per - 0.05ms/0.01 per tick

https://timings.aikar.co/?id=268e1e5f4f104bb3b1181e48c1320621

Using the latest Claytech, latest cscore and slimefun (auto update), 1.16.1 server, latest paper (auto update)

**Comment by ClayCoffee** [comment]
normal

**Comment by bobhenl** [comment]
But maybe you can try improve a little bit?

**Comment by ClayCoffee** [comment]
No
