### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wojiaocrazy** [ClayCoffee/ClayTech#67]
** Describe 描述 **
报错

** To Reproduce 如何复现 **

** Running Environment 运行环境 **
1.16.1spigot

** Screenshots 截图 **

> 
![1](https://user-images.githubusercontent.com/69898251/90620283-d3f62980-e244-11ea-9dc7-dc9ea9618773.png)

**Comment by wojiaocrazy** [comment]
> ** Describe 描述 **
> 报错
> 
> ** To Reproduce 如何复现 **
> 
> ** Running Environment 运行环境 **
> 1.16.1spigot
> 
> ** Screenshots 截图 **
> 
> > 
> 
> ![1](https://user-images.githubusercontent.com/69898251/90620283-d3f62980-e244-11ea-9dc7-dc9ea9618773.png)

**Comment by ClayCoffee** [comment]
？人类迷惑行为
没有版本，没有任何信息
一看就是粘液科技没更新
请看看帖子里的Q&A再来
粘土科技已经暂时不更新了
