### ISSUE TITLE
[BUG]给宇航服胸甲和护腿充氧的时候会变成头盔和靴子

### ISSUE THREAD

**Issue by RONGYAO749CN** [ClayCoffee/ClayTech#7]
** Describe 描述 **
如题，给宇航服充氧的时候就会出现标题所述情况

** To Reproduce 如何复现 **
给宇航服护甲和宇航服护腿充氧

** Running Environment 运行环境 **
Windows 10 1909
Paper 1.15.2 b161
Slimefun-v4.3-NIGHTLY-200401

** Screenshots 截图 **

**Comment by RONGYAO749CN** [comment]
原谅我描述的不够详细
截图确实截不了，但是刚刚测试的时候
发现胸甲和护腿在充氧的时候有一定概率互换
充满氧后则可能会变成头盔或者靴子

**Comment by ClayCoffee** [comment]
无法复现，整不出来
建议升级CS CoreLib版本

**Comment by ClayCoffee** [comment]
如果升级后还是出现你所说的这个情况的话
请发个复现视频
