### ISSUE TITLE
[BUG]黏土融合器會消失

### ISSUE THREAD

**Issue by Frodwo** [ClayCoffee/ClayTech#72]
** Describe 描述 **
玩家回報融合器在放置時 使用時 以及放著不動時會有一定機率消失 原本的位子變成空氣方塊

** To Reproduce 如何复现 **

** Running Environment 运行环境 **
ClayTech版本 : 1.2.7  slimefunv版本 : 4.3-dev-200810
有WipeGhostSlimefunBlock 異域花園跟儲存單元
沒有任何清除插件 領地管理是GriefPrevention

** Screenshots 截图 **
![image](https://user-images.githubusercontent.com/70096255/90977442-2b173980-e578-11ea-8c62-119d51b58541.png)

**Comment by ClayCoffee** [comment]
您好，在伺服器的控制台裡有報錯嗎？

**Comment by ClayCoffee** [comment]
如果沒有，請檢查一下plugins/Slimefun/error-reports資料夾

**Comment by ClayCoffee** [comment]
如果可以的話，請把裡面的文檔壓縮成zip檔發給我

**Comment by Frodwo** [comment]
此處是error-reports資料夾檔案

ClayCoffee <notifications@github.com> 於 2020年8月27日 週四 下午8:05寫道：
