### ISSUE TITLE
[BUG]世界生成报错

### ISSUE THREAD

**Issue by xiaozhiyl** [ClayCoffee/ClayTech#79]
请问这个要怎么解决？
![QQ截图20200905224206](https://user-images.githubusercontent.com/57853246/92307582-08e6d800-efca-11ea-979f-a0ef8219dd61.png)
![QQ截图20200905224220](https://user-images.githubusercontent.com/57853246/92307585-0d12f580-efca-11ea-99e3-22acc2bb82cb.png)

**Comment by ClayCoffee** [comment]
这个不是错误
无法解决，是由Slimefun和地图加载导致的性能问题，请考虑升级cpu或为世界设置边界，预先生成边界内地图。
