### ISSUE TITLE
[BUG] Clayfuel / Geominer

### ISSUE THREAD

**Issue by DepressedMilkshake** [ClayCoffee/ClayTech#8]
** Describe 描述 **
No way to get clay fuel, or doesn't show up on the GEO miner resource list. The description for playful and mixed rocket fuel also doesn't describe the way to get the items for the rocket fuel.

** Screenshots 截图 **
<img width="960" alt="2020-04-06_15 30 09" src="https://user-images.githubusercontent.com/63175510/78597604-d323a480-781b-11ea-9b41-79d18ab5e5d9.png">

**Comment by ClayCoffee** [comment]
This might be a bug, you can create a new world to solve this problem temporarily

**Comment by ClayCoffee** [comment]
The resource can be found in the new world

**Comment by DepressedMilkshake** [comment]
Got it, i found some on the moon and some on the overworld after making a new world
