### ISSUE TITLE
[BUG] clay tech conflic with plugins village defense (minigames) 

### ISSUE THREAD

**Issue by Scarlet2031** [ClayCoffee/ClayTech#83]
** Describe 描述 **
every time a player kills a zombie while playing in village defense, it will make spaming on the console

** To Reproduce 如何复现 **
I have contacted the owner of Plugins Village Defense., but he said it was clear that the problem with clay tech itself

** Running Environment 运行环境 **
![image](https://user-images.githubusercontent.com/64282946/93035972-ae541880-f668-11ea-8250-65e4ead0e4d6.png)

![image](https://user-images.githubusercontent.com/64282946/93036011-cdeb4100-f668-11ea-8beb-8d9994b5165d.png)

** Screenshots 截图 **
https://pastebin.com/r7M7cG4e

**Comment by ClayCoffee** [comment]
Fixed
