### ISSUE TITLE
Element Extractor Not Working[BUG]

### ISSUE THREAD

**Issue by Mabit100** [ClayCoffee/ClayTech#85]
** Describe 描述 **
When placing sand, coal.....into the element extractor nothing happens. See Screenshot As you can see the machine has power. I have tried giving it 64 of an item and only 10 of an item. 

** To Reproduce 如何复现 **
Place Element Extractor and add item

** Running Environment 运行环境 **
Paper v1.16 R2 (202)
Slimefun RC-16
Claytech 1.2.15-hotfix

** Screenshots 截图 **
![image](https://user-images.githubusercontent.com/21134218/95042643-7756ad00-06d2-11eb-98eb-fd8deed36fe0.png)
![image](https://user-images.githubusercontent.com/21134218/95042733-b258e080-06d2-11eb-8eda-741f555d5139.png)

**Comment by ClayCoffee** [comment]
Wrong usage. It's not a bug. You should put an Element Unit to the slot.
