### ISSUE TITLE
[BUG] Rocket wont launch

### ISSUE THREAD

**Issue by DepressedMilkshake** [ClayCoffee/ClayTech#9]
** Describe 描述 **
Rocket won't launch, we've placed it on a rocket launcher and fueled it, however it doesn't let us right-click and it just spits out "unspp" and nothing else.

Rocket and rocket launcher don't tell us how to actually launch it, like if its a specific launch pad design we need to make.

CMoon has also been set to True in planets.yml

** Screenshots 截图 **
![2020-04-07_20 26 52](https://user-images.githubusercontent.com/63175510/78731764-997f9600-790e-11ea-894b-ff1011cc67ff.png)

**Comment by ClayCoffee** [comment]
This is not a ClayTech bug.Are you using PlotSquared?The plugin doesn't support it.
