### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by qianchen1010** [ClayCoffee/ClayTech#92]
Java Environment:
  Operating System: Windows Server 2016
  Java Version: 1.8.0_221

Server Software: Paper
  Build: git-Paper-371 (MC: 1.15.2)
  Minecraft: 1.15.2-R0.1-SNAPSHOT

Slimefun Environment:
  CS-CoreLib vDEV - 88 (git 6a39a9e7)
  Slimefun v4.3-dev-200720
  Caused by: ClayTech v1.2.17

Installed Addons (12)
  + Barrels 1.15
  + ExtraGear DEV - 12 (git 4570ea2c)
  - ClayTech 1.2.17
  - TranscEndence DEV - 16 (git df2e8999)
  + HotbarPets UNOFFICIAL
  + SlimefunLuckyBlocks UNOFFICIAL
  + ExoticGarden DEV - KarStudio 1.1.1
  + ExtraTools 1.1
  + SlimyTreeTaps 1.0.0
  + PrivateStorage 1.3.0
  + CMI 8.7.8.0
  + SoundMuffler DEV - 12 (git 7303b3a9)

Installed Plugins (76):
  + EntityTrackerFixer 1.2.2
  + JustTPA 1.0.0
  + AdvancedLogin 3.11
  + AegisClear 1.5.0
  + ServerBooster 1.0.34
  + AggressiveAnimals 2.5
  + PlaceholderAPI 2.10.6
  + DeluxeJoin 2.8.0
  + PlugMan 2.1.7
  + Authenticate 1.3
  + GrItemTags 1.0.8
  + AvlPlus 1.0-SNAPSHOT
  + ChestSort 8.12.2
  + ItemStackAPI 1.0
  + SkinsRestorer 13.8.4
  + NotBoom 1.3
  + WorldNoDrop 1.0.0
  + NoteBlockAPI 1.5.0
  + ViaVersion 3.0.1
  + LightAPI 3.4.4
  + JukeBox 1.18.1
  + LuckPerms 5.1.63
  + WorldEdit 7.1.0;8e55131
  + HealthBar 1.8.3
  + SAML 2.0.0
  + UltimateTimber 2.0.8
  + LaggRemover 2.0.5
  + ProtocolLib 4.5.1
  + OmNom 1.1.0
  + Poop 2.1.0
  + DeluxeMenus 1.12.0
  + MiaoBoard 2.5.0-git-fdf05fc1c0c21b8fb30cf99ccb58d20e396ebfc7
  + LimitPillagers 2.12.0
  + CS-CoreLib DEV - 88 (git 6a39a9e7)
  + DemonPickItem 1.3
  + Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  + MiaoChat 1.9.2-git-c25a667571b8d0f64037c7e6cb23f33bfba8a05f
  + OhMyCmd 1.1.0
  + Matrix 5.2.1
  + PlayerPoints 2.1.4
  + WorldGuard 7.0.3;5407315
  + Spartan Build 363.1
  + PlayerTitle 1.1.6
  + ProtectionLib 0.9.9
  + LagAssist 2.21.1
  + ShopGUIPlus 1.31.2
  + AtMe 1.2.0
  + AACAdditionPro 6.0.1
  + Citizens 2.0.26-SNAPSHOT (build 1821)
  + TradeMe 6.0.4.0
  + EmeraldEnchants 2.1
  + BentoBox 1.13.1
  + AdvancedAchievements 6.1.3
  + CitizensCMD 2.4
  + Slimefun 4.3-dev-200720
  + JetsMinions 6.1.2
  + Barrels 1.15
  + ExtraGear DEV - 12 (git 4570ea2c)
  - ClayTech 1.2.17
  - TranscEndence DEV - 16 (git df2e8999)
  + Multiverse-Core 4.1.0-b775
  + HotbarPets UNOFFICIAL
  + SlimefunLuckyBlocks UNOFFICIAL
  + ExoticGarden DEV - KarStudio 1.1.1
  + ExtraTools 1.1
  + SlimyTreeTaps 1.0.0
  + PrivateStorage 1.3.0
  + CMI 8.7.8.0
  + SoundMuffler DEV - 12 (git 7303b3a9)
  + FurnitureLib 2.2.9
  + TAB 2.8.1
  + DiceFurniture 3.4.2
  + InteractionVisualizer 1.11.3
  + BossShopPro 2.0.8
  + GuiShopManager 1.1.2
  + CMIPaperLib 1.0.0

Block Info:
  World: bskyblock_world
  X: 1608
  Y: 118
  Z: -12
  Material: RED_STAINED_GLASS
  Block Data: org.bukkit.craftbukkit.v1_15_R1.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_15_R1.block.CraftBlockState
Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: CLAY_ELECTRIC_STONE_CRUSHER
  Inventory: true
  Data: {"energy-charge":"128","id":"CLAY_ELECTRIC_STONE_CRUSHER"}

Stacktrace:

java.lang.NoSuchMethodError: cn.claycoffee.ClayTech.implementation.abstractMachines.ANewContainer.getCharge(Lorg/bukkit/Location;)I
	at cn.claycoffee.ClayTech.implementation.abstractMachines.ANewContainer.tick(ANewContainer.java:41)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$2.tick(AContainer.java:227)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:122)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tick(TickerTask.java:110)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:69)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$start$4(TickerTask.java:176)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by ClayCoffee** [comment]
版本太低，无效
