### ISSUE TITLE
Improvement locale 

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#95]
** Describe 描述 **
Hi, players have built machine  CLAY_SPACESUIT_OXYGEN_INJECTOR and it doesn't fulfill SPACESUIT with energy even when there are leaves above.

** To Reproduce 如何复现 **
Build machine spacesuit oxygen injector and put there spacesuit, leaves above it and see if it works.

** Running Environment 运行环境 **
![image](https://user-images.githubusercontent.com/18662086/100216193-49435b80-2f12-11eb-8a21-cbfd4fc2b186.png)
ClayTech 1.2.19

** Screenshots 截图 **
![image](https://user-images.githubusercontent.com/18662086/100216100-2b75f680-2f12-11eb-82f0-d567eaaeb147.png)

![image](https://user-images.githubusercontent.com/18662086/100216102-2ca72380-2f12-11eb-8da2-1d43461fa72b.png)

![image](https://user-images.githubusercontent.com/18662086/100216107-2d3fba00-2f12-11eb-9936-bf2040b3a348.png)

**Comment by ClayCoffee** [comment]
What's the locale in config.yml?

**Comment by bobhenl** [comment]
Locale: en-US

**Comment by bobhenl** [comment]
Mhm?

**Comment by bobhenl** [comment]
That's probably cause I edited messages a little bit, but it should be supported.... it shouldn't be locked on name and it should normally accept any changes made to local files... @ClayCoffee

**Comment by ClayCoffee** [comment]
> That's probably cause I edited messages a little bit, but it should be supported.... it shouldn't be locked on name and it should normally accept any changes made to local files... @ClayCoffee

OK.

**Comment by bobhenl** [comment]
Btw still not fixed @ClayCoffee
