### ISSUE TITLE
[NewFeature] Way to limit CMARS and CMOON size (worldborder) when teleporting there + pregenerating

### ISSUE THREAD

**Issue by bobhenl** [ClayCoffee/ClayTech#96]
** Describe / 描述 **
Hi, could you please add way to respect wordborder of these worlds, so players couldn't arrive by rocket after worldborder? And maybe also way to pregenerate these worlds? I tried it with chunkmaster and it didn't work from some reason. Server was crashing.... and normally other worlds were normally pregenerated, also with custom generators, so I don't understand why these two worlds couldn't be pregenerated by chunkmaster, when I set there /worldborder set 5000 on CMARS and CMOON and then /chunkmaster generate CMOON and CMARS. The problem is that from some reason world border reverted to 60000000 blocks, but it 's causing a little bit lags, as you can see here https://timings.aikar.co/?id=ed35d7212292453eaba9ae58655960ca#timings

**Comment by ClayCoffee** [comment]
#94
