### ISSUE TITLE
Clay Electric Copier

### ISSUE THREAD

**Issue by goraffe** [ClayCoffee/ClayTech#98]
I can’t seem to find what item I need or what the Electric clay copier actually copies. I would appreciate some sort of guide or help with the machine and how to use it

**Comment by goraffe** [comment]
If it’s only purpose is to copy written books or book and quills with words then what is the point of this machine existing? We have been able to do that in vanilla Minecraft since 1.7.2. My suggestion is make it so you can copy enchanted books with the machine.

**Comment by ClayCoffee** [comment]
copy books
